data <- read.csv("household_power_consumption.txt", header=TRUE, sep=';', na.strings="?")
data$Date <- as.Date(data$Date, format="%d/%m/%Y")
data<-subset(data, Date =="2007-02-01" | Date=="2007-02-02")
data$Global_active_power <- as.numeric(data$Global_active_power)
data$DateTime <- as.POSIXct(paste(data$Date, data$Time))
png("plot2.png", height=480, width=480)
par(mfrow = c(1,1))
plot(data$Global_active_power~data$DateTime, type="l", ylab="Global Active Power (kilowatts)", xlab="")
dev.off()